### ISSUE TITLE
Nullpomino suddenly closes when trying to play modes from ModePile

### ISSUE THREAD

**Issue by KirbyJoe** [Shots243/ModePile#8]
I followed the instructions correctly to install ModePile, but Nullpomino suddenly closes when I try to play a mode from ModePile. I'm using Slick Instance of Nullpomino 7.5.0.

**Comment by Shots243** [comment]
If it is possible, could you provide more information of what was happening at the time of the crash or a copy of the log file at the time of the crash (located log/log_slick.txt in the NullpoMino install folder)?

**Comment by KirbyJoe** [comment]
Here it is:
[log_slick.txt](https://github.com/Shots243/ModePile/files/4585174/log_slick.txt)

**Comment by Shots243** [comment]
Has the game been run again after the crash? The log clears at every game start and there is no error message reported in this copy.

If the game crashes again, would it be possible to send the log file immediately after?

I apologise for any inconvenience.

**Comment by KirbyJoe** [comment]
Sorry about that, the log file I posted is a wrong one, which was created when I didn't play any gamemode and closed the game normally.
Anyway, I tried to play Pong mode this time. The game didn't run again automatically after the crash.
[log_slick.txt](https://github.com/Shots243/ModePile/files/4585200/log_slick.txt)

**Comment by Shots243** [comment]
So the error appears to happen here.

```
20-05-06 15:55:59,379 [main] DEBUG mu.nu.nullpo.game.play.GameManager: GameManager constructor called
20-05-06 15:55:59,380 [main] ERROR mu.nu.nullpo.gui.slick.StateInGame: Couldn't find mode:PONG
20-05-06 15:55:59,380 [main] DEBUG mu.nu.nullpo.game.play.GameManager: GameManager init()
20-05-06 15:55:59,658 [main] ERROR Slick: 
java.lang.NullPointerException
	at mu.nu.nullpo.gui.slick.StateInGame.startNewGame(StateInGame.java:161)
	at mu.nu.nullpo.gui.slick.StateSelectRuleFromList.onDecide(StateSelectRuleFromList.java:187)
	at mu.nu.nullpo.gui.slick.DummyMenuChooseState.updateImpl(DummyMenuChooseState.java:94)
	at mu.nu.nullpo.gui.slick.BaseGameState.update(BaseGameState.java:71)
	at org.newdawn.slick.state.StateBasedGame.update(StateBasedGame.java:268)
	at org.newdawn.slick.ScalableGame.update(ScalableGame.java:135)
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:657)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:412)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:322)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
20-05-06 15:55:59,661 [main] ERROR Slick: 
org.newdawn.slick.SlickException: Game.update() failure - check the game code.
	at org.newdawn.slick.GameContainer.updateAndRender(GameContainer.java:663)
	at org.newdawn.slick.AppGameContainer.gameLoop(AppGameContainer.java:412)
	at org.newdawn.slick.AppGameContainer.start(AppGameContainer.java:322)
	at mu.nu.nullpo.gui.slick.NullpoMinoSlick.main(NullpoMinoSlick.java:357)
20-05-06 15:55:59,742 [main] DEBUG mu.nu.nullpo.gui.slick.NullpoMinoSlick: stopObserverClient called
```

This error usually happens when the game fails to locate the path of the mode. Just to make sure, are the folders `zeroxfc`, `bin` and `mandl` inside the `bin` folder in the NullpoMino install? And are all of the mode classpaths added to `[NullpoMino]/config/list/mode.lst`?

**Comment by KirbyJoe** [comment]
The folders are inside the `bin` folder in the Nullpomino install.
I also added all of the mode classpaths to `NullpoMino]/config/list/mode.lst`.
I removed the blank lines between the classpaths and now it's working fine.

**Comment by Shots243** [comment]
Ah, that might be the cause.
The NullpoMino list parsers abort on blank lines and stop reading after the first empty line.
